---
# Prerequisite tasks that have to be done on each remote host
# before any role is applied
- name: Prerequisites | ensure apt cache is up to date
  action: apt update_cache=yes

- name: Prerequisites | Install prerequisite packages
  action: apt pkg={{ item }} state=latest
  with_items:
    - python-apt
    - software-properties-common
    - python-pycurl
    - g++
    - make
    - language-pack-en
    - mc
    - git
    - mercurial

- name: Prerequisites | Set up utf-8 locale
  action: command update-locale {{ item }}={{ locale }}
  with_items:
    - LANG
    - LANGUAGE
    - LC_CTYPE
    - LC_NUMERIC
    - LC_TIME
    - LC_COLLATE
    - LC_MONETARY
    - LC_MESSAGES
    - LC_PAPER
    - LC_NAME
    - LC_ADDRESS
    - LC_TELEPHONE
    - LC_MEASUREMENT
    - LC_IDENTIFICATION
    - LC_ALL
