"""add fixtures

Revision ID: 0c6de0437b27
Revises: 75b78a5e83a9
Create Date: 2016-03-03 06:45:43.814497

"""

# revision identifiers, used by Alembic.
revision = '0c6de0437b27'
down_revision = '75b78a5e83a9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import text
    from assignment.fixtures import read_csv
    traits = read_csv('./assignment/fixtures/dataset.csv')
    people = {}
    conn = op.get_bind()
    for trait_id, trait, matched in traits:
        # Not optimal, but ok for the purpose of the assignment
        conn.execute(text('INSERT INTO traits (name) VALUES (:trait)'),
                     trait=trait)
        for match in matched:
            people.setdefault(match, []).append(trait_id)

    for person, trait_ids in people.items():
        conn.execute(text('INSERT INTO people (name, traits) VALUES (:name, :trait_ids)'),
                     name=person, trait_ids=trait_ids)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
