"""traits index

Revision ID: 75b78a5e83a9
Revises: 22c911d2bf6d
Create Date: 2016-03-03 04:10:06.665983

"""

# revision identifiers, used by Alembic.
revision = '75b78a5e83a9'
down_revision = '22c911d2bf6d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX people_traits_rdtree_idx ON people USING GIST (traits gist__intbig_ops);')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
