"""traits intarray

Revision ID: d6ae559902f7
Revises: 44bf45005346
Create Date: 2016-03-03 00:29:12.736321

"""

# revision identifiers, used by Alembic.
revision = 'd6ae559902f7'
down_revision = '44bf45005346'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('traits', postgresql.ARRAY(sa.Integer(), dimensions=1), server_default='{}', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'traits')
    ### end Alembic commands ###
